Project/app/urls.py
from re import DEBUG
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns = [
        *urlpatterns,
    ] + debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'  # アプリケーション名を指定してURL名の衝突を防ぐ

urlpatterns = [
    path('search/', views.catalog, name='search'),  # 検索結果を表示するルート
    path('<slug:category_slug>/', views.catalog, name='index'),  # カテゴリー別のカタログページを表示するルート
    path('product/<slug:product_slug>/', views.product, name='product'),  # 商品詳細ページを表示するルート
]

Project/main/urls.py
from django.urls import path

from main import views

app_name = 'main'  # アプリケーション名を指定することで、URL名の衝突を防ぐ

urlpatterns = [
    path('', views.index, name='index'),  # メインページへのルート
    path('about/', views.about, name='about'),  # 会社概要ページへのルート
]

Project/users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),  # ログインページへのルート
    path('registration/', views.registration, name='registration'),  # 新規登録ページへのルート
    path('profile/', views.profile, name='profile'),  # プロファイル管理ページへのルート
    path('users-cart/', views.users_cart, name='users_cart'),  # ユーザーのカートページへのルート
    path('logout/', views.logout, name='logout'),  # ログアウト機能へのルート
]

Project/templates/base.html
{% load static %}
{% load goods_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- BootstrapとカスタムCSSの読み込み -->
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
    <!-- 各プラットフォーム用のファビコン -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "deps/favicon/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/favicon/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "deps/favicon/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "deps/favicon/site.webmanifest" %}">
    <title>{{ title }}</title>
</head>

<body>
    <header>
        <!-- ナビゲーションバーの定義 -->
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url "main:index" %}">メインページ</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <!-- ドロップダウンメニュー -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                インフォメーション
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item text-white" href="#">配送情報</a></li>
                                <li><a class="dropdown-item text-white" href="#">連絡先</a></li>
                                <li><a class="dropdown-item text-white" href="{% url "main:about" %}">会社概要</a></li>
                            </ul>
                        </li>
                        <!-- ショッピングカートリンク -->
                        <li class="nav-item">
                            <a class="nav-link text-white" href="{% url "user:users_cart" %}">カート</a>
                        </li>
                        <!-- ログインリンク -->
                        {% if not user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link text-white" href="{% url "user:login" %}">ログイン</a>
                            </li>
                        {% else %}
                        <!-- プロファイルのドロップダウンメニュー -->
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                    プロファイル
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item text-white" href="{% url "user:users_cart" %}">カート</a></li>
                                    <li><a class="dropdown-item text-white" href="{% url "user:profile" %}">プロファイル表示</a>
                                    </li>
                                    {% if user.is_admin or user.is_staff %}
                                        <li><a class="dropdown-item text-white" href="{% url "admin:index" %}">管理画面</a></li>
                                    {% endif %}
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item text-white" href="{% url "user:logout" %}">ログアウト</a></li>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>
                    <!-- 検索フォーム -->
                    <form class="d-flex" role="search" action="{% url "catalog:search" %}" method="GET">
                        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">KENSAKU</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>

    <section>
        <div class="container">
            <!-- 固定されたカタログとカートボタン -->
            <div class="row mt-1 position-fixed z-3">
                <!-- カタログドロップダウン -->
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        カタログ
                        <img class="mx-1" src="{% static "deps/icons/grid-fill.svg" %}" alt="Catalog Icon" width="16"
                            height="16">
                    </button>
                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                        {% tag_categories as categories%}
                        {% for category in categories %}
                        <li><a class="dropdown-item text-white" href="{% url "catalog:index" category.slug %}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- カートボタン、モーダルウィンドウを表示 -->
                {% block modal_cart %}{% endblock  %}
                <!-- モーダルウィンドウ終了 -->
            </div>
        </div>
        <!-- ページコンテンツ -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- 空のブロック、自由に使用可能 -->
                </div>
                <div class="col-lg-10">
                    {% include "notifications.html" %}
                    <!-- ページのコンテンツ -->
                    {% block content %}
                    {% endblock content %}
                </div>
            </div>
        </div>
    </section>
    <!-- フッター -->
    <div class="clear" style='clear: both; height: 60px;'></div>
    <footer class="py-4 bg-dark" style="z-index: 1000;">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; IMINOV KAMIL 2024</p>
        </div>
    </footer>
    <!-- スクリプトの読み込み -->
    <script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "deps/js/jquery-ajax.js" %}"></script>
    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
</body>

</html>

Project/templates/cart_button.html
{% load static %}
{% load carts_tags %}
{% user_carts request as carts %}

<div>
    <!-- カートボタン、クリックでモーダルウィンドウを表示 -->
    <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton"
        aria-expanded="false">
        <img class="mx-1" src="{% static "deps/icons/basket2-fill.svg" %}" alt="Catalog Icon" width="24"
            height="24">
        <!-- カート内の商品数を表示 -->
        <span id="goods-in-cart-count">{{ carts.total_quantity }}</span>
    </button>
</div>

<!-- カートのモーダルウィンドウ -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <!-- モーダルウィンドウを閉じるボタン -->
                <button type="button" class="btn-close" data-bs-dismiss="modal"
                    aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h3 class="text-center mb-4">カート</h3>
                <div class="container" id="cart-items-container">
                    <!-- カートの内容 -->
                    {% include "cart.html" %}
                    <!-- カートの内容終了 -->
                </div>
                {% if carts %}
                <!-- 注文確認ページへのリンク -->
                <a class="btn btn-dark" href="orders/create_order.html">
                    注文確認
                </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

Project/templates/notifications.html
{% load static %}

<!-- フォーム全体に関するエラーが存在する場合 -->
{% if form.non_field_errors %}
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <!-- エラーメッセージの表示 -->
                <div class="alert alert-danger alert-dismissible fade show custom-shadow" role="alert">
                    {{ form.non_field_errors }}
                    <!-- 閉じるボタン -->
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            </div>
        </div>
    </div>
{% endif %}

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <!-- 成功メッセージの表示 -->
                    <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow" role="alert">
                        {{ message }}
                    </div>
                    {% endif %}
                    {% if message.tags == 'warning' %}
                    <!-- 警告メッセージの表示 -->
                    <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-danger fade show custom-shadow" role="alert">
                        {{ message }}
                    </div>
                    {% endif %}
                {% endfor %}
            {% else %}
            <!-- jQueryによる動的な通知用の要素 -->
            <div id="jq-notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow" style="display: none;" role="alert">
            </div>
            {% endif %}
        </div>
    </div>
</div>