Project/app/urls.py
from re import DEBUG
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns = [
        *urlpatterns,
    ] + debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),  # ログインページへのルート
    path('registration/', views.registration, name='registration'),  # 新規登録ページへのルート
    path('profile/', views.profile, name='profile'),  # プロファイル管理ページへのルート
    path('users-cart/', views.users_cart, name='users_cart'),  # ユーザーのカートページへのルート
    path('logout/', views.logout, name='logout'),  # ログアウト機能へのルート
]

Project/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# カスタムユーザーモデルを定義
class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='プロファイル画像')  # プロファイル画像用のフィールド

    class Meta:
        db_table = 'user'  # データベースのテーブル名を指定
        verbose_name = 'ユーザー'  # 管理画面での単数形の名前
        verbose_name_plural = 'ユーザー'  # 管理画面での複数形の名前
    
    # ユーザー名を返すメソッド、管理画面やシェルでの表示に使用
    def __str__(self):
        return self.username

Project/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from users.models import User

# ユーザーログインフォームを定義
class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']  # フォームに表示するフィールド

# ユーザー登録フォームを定義
class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']  # フォームに表示するフィールド

    first_name = forms.CharField()  # 名前入力フィールド
    last_name = forms.CharField()  # 苗字入力フィールド
    username = forms.CharField()  # ユーザー名入力フィールド
    email = forms.CharField()  # メールアドレス入力フィールド
    password1 = forms.CharField()  # パスワード入力フィールド
    password2 = forms.CharField()  # パスワード確認フィールド

# ユーザープロファイルフォームを定義
class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['image', 'first_name', 'last_name', 'username', 'email']  # フォームに表示するフィールド

    image = forms.ImageField(required=False)  # プロファイル画像フィールド（任意）
    first_name = forms.CharField()  # 名前入力フィールド
    last_name = forms.CharField()  # 苗字入力フィールド
    username = forms.CharField()  # ユーザー名入力フィールド
    email = forms.CharField()  # メールアドレス入力フィールド

Project/users/views.py
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from users.forms import ProfileForm, UserLoginForm, UserRegisterForm

# ログイン機能を提供するビュー
def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                messages.success(request, f"{username}様、ログイン成功")

                # ログイン後にリダイレクト
                if request.POST.get('next', None):
                    return HttpResponseRedirect(request.POST.get('next'))
                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()

    context = {
        'title': 'ログイン',
        'form': form
    }
    return render(request, 'users/login.html', context)

# ユーザー登録機能を提供するビュー
def registration(request):
    if request.method == 'POST':
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)
            messages.success(request, f"{user.username}様、新規登録成功")
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegisterForm()

    context = {
        'title': 'ユーザー登録',
        'form': form
    }
    return render(request, 'users/registration.html', context)

# プロファイル管理機能を提供するビュー（ログインが必要）
@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "保存成功")
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = ProfileForm(instance=request.user)
    
    context = {
        'title': 'プロファイル',
        'form': form
    }
    return render(request, 'users/profile.html', context)

# ユーザーのカートページを表示するビュー
def users_cart(request):
    return render(request, 'users/users_cart.html')

# ログアウト機能を提供するビュー（ログインが必要）
@login_required
def logout(request):
    messages.success(request, "ログアウト成功")
    auth.logout(request)
    return redirect(reverse('main:index'))

Project/users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block modal_cart %}
{% include "cart_button.html" %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                    <!-- ログイン画面のタイトル -->
                    <h2 class="text-center mb-4">ログイン画面</h2>
                    <!-- ログインフォーム -->
                    <form action="{% url "user:login" %}" method="POST">
                        {% csrf_token %}
                        <!-- リダイレクト用のhiddenフィールド -->
                        {% if request.GET.next %}
                            <input type="hidden" name="next" value="{{ request.GET.next }}">
                        {% endif %}

                        <!-- ユーザー名フィールド -->
                        <div class="mb-3">
                            <label for="id_username" class="form-label">ユーザー名</label>
                            <input type="text" class="form-control" value="{% if form.username.value %}{{ form.username.value }}{% endif %}" name="username" id="id_username" placeholder="ユーザー名を入力してください" required>
                        </div>
                        <!-- パスワードフィールド -->
                        <div class="mb-3">
                            <label for="id_password" class="form-label">パスワード</label>
                            <input type="password" class="form-control" name="password" id="id_password" placeholder="パスワードを入力してください" required>
                        </div>

                        <!-- ログインボタン -->
                        <button type="submit" class="btn btn-dark btn-block">ログイン</button> 
                    </form>
                    <div class="mt-3">
                        <a href="#">パスワードを忘れた</a> | <a href="{% url "user:registration" %}">新規登録</a>
                    </div>
                    <hr>
                    <div class="text-center">
                        <p>下記経由でログインできます</p>
                        <!-- ソーシャルログインボタン -->
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static "deps/icons/google.svg" %}" alt="Catalog Icon" width="16" height="16">
                            Google
                        </a>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static "deps/icons/facebook.svg" %}" alt="Catalog Icon" width="16" height="16">
                            Facebook
                        </a>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static "deps/icons/github.svg" %}" alt="Catalog Icon" width="16" height="16">
                            GitHub
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Project/users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}

{% block content %}
    <div class="row">
        <div class="container mt-5">
            <div class="row">
                <!-- ユーザープロファイルを表示するセクション -->
                <div class="col-md-5">
                    <div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">ユーザープロファイル</h3>
                        <form action="{% url "user:profile" %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12 mb-3 text-center">
                                    {% if user.image %}
                                        <!-- プロファイル画像がある場合は表示 -->
                                        <img src="{{ user.image.url }}"
                                                alt="プロファイル画像" class="img-fluid rounded-circle"
                                                style="max-width: 150px;">
                                    {% else %}
                                        <!-- プロファイル画像がない場合はデフォルトの画像を表示 -->
                                        <img src="{% static "deps/images/baseavatar.jpg" %}"
                                            alt="プロファイル画像" class="img-fluid rounded-circle"
                                            style="max-width: 150px;">
                                    {% endif %}
                                    <!-- プロファイル画像のアップロード -->
                                    <input type="file" class="form-control mt-3" id="id_image" name="image"
                                        accept="image/*">
                                    {% if form.image.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.image.errors }}</div>
                                    {% endif %}
                                </div>
                                <!-- 各種フィールドの入力フォーム -->
                                <div class="col-md-12 mb-3">
                                    <label for="id_first_name" class="form-label">ファーストネーム*</label>
                                    <input type="text" class="form-control" id="id_first_name"
                                        name="first_name"
                                        placeholder="ファーストネームを入力してください" value="{{ form.first_name.value }}" required>
                                        {% if form.first_name.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                        {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_last_name" class="form-label">ラストネーム*</label>
                                    <input type="text" class="form-control" id="id_last_name"
                                        name="last_name"
                                        placeholder="ラストネームを入力してください" value="{{ form.last_name.value }}" required>
                                        {% if form.last_name.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                        {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_username" class="form-label">ユーザー名*</label>
                                    <input type="text" class="form-control" id="id_username"
                                        name="username"
                                        placeholder="ユーザー名を入力してください" value="{{ form.username.value }}" required>
                                        {% if form.username.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                        {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_email" class="form-label">Email*</label>
                                    <input type="email" class="form-control" id="id_email"
                                        placeholder="メールアドレスを入力してください" value="{{ form.email.value }}"
                                        name="email"
                                        required>
                                        {% if form.email.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                        {% endif %}
                                </div>
                            </div>
                            <button type="submit" class="btn btn-dark">保存</button>
                        </form>
                    </div>
                </div>
                <!-- ユーザーのカートを表示するセクション -->
                <div class="col-md-7">
                    {% user_carts request as carts %}
                    <div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">カート</h3>
                        <div class="container" id="cart-items-container">
                            <!-- カートの内容を表示する -->
                            {% include "cart.html" %}
                        </div>
                        {% if carts %}
                        <a class="btn btn-dark" href="#">
                            注文確認
                        </a>
                        {% endif %}
                    </div>
                </div>
                <!-- ユーザーの注文履歴を表示するセクション -->
                {% comment %} <div class="col-md-12">
                    <div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">Мои заказы</h3>
                        <!-- 注文履歴をアコーディオンで表示 -->
                        <div class="container">
                            <div class="accordion" id="accordionExample">
                                <div class="accordion-item">
                                    <h2 class="accordion-header" id="heading1">
                                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse1" aria-expanded="false" aria-controls="collapse1">
                                            Заказ № 256 - 09 сентября 2023 9:04 | Статус:<strong class="mx-2"> В обработке</strong>
                                        </button>
                                    </h2>
                                    <div id="collapse1" class="accordion-collapse collapse show" aria-labelledby="heading1" data-bs-parent="#accordionExample">
                                        <div class="accordion-body">
                                            <table class="table table-dark table-hover">
                                                <thead>
                                                    <tr>
                                                        <th>Товар</th>
                                                        <th>Количество</th>
                                                        <th>Цена</th>
                                                        <th>Общая стоимость</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <td><a class="text-white" href="#">Комплект стол и три стула</a></td>
                                                        <td>1</td>
                                                        <td>255.00 $</td>
                                                        <td>255.00 $</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                            <div class="d-flex justify-content-between">
                                                <p><strong>Итого:</strong></p>
                                                <p><strong>255.00 $</strong></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="accordion-item">
                                    <h2 class="accordion-header" id="heading2">
                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse2" aria-expanded="false" aria-controls="collapse2">
                                            Заказ № 248 - 01 августа 2023 11:28 | Статус: <strong>Получен</strong>
                                        </button>
                                    </h2>
                                    <div id="collapse2" class="accordion-collapse collapse" aria-labelledby="heading2" data-bs-parent="#accordionExample">
                                        <div class="accordion-body">
                                            <table class="table table-dark table-hover">
                                                <thead>
                                                    <tr>
                                                        <th>Товар</th>
                                                        <th>Количество</th>
                                                        <th>Цена</th>
                                                        <th>Общая стоимость</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <td><a class="text-white" href="#">Стул офисный</a></td>
                                                        <td>2</td>
                                                        <td>30.00 $</td>
                                                        <td>60.00 $</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- 注文履歴のセクション終了 -->
                    </div>
                </div> {% endcomment %}
            </div>
        </div>
    </div>
{% endblock %}

Project/users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}

{% block modal_cart %}
{% include "cart_button.html" %}
{% endblock  %}

{% block content %}
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                    <!-- 登録画面のタイトル -->
                    <h2 class="text-center mb-4">新規登録</h2>
                    <!-- 新規登録フォーム -->
                    <form action="{% url "user:registration" %}" method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <!-- 各フィールドの入力フォーム -->
                            <div class="col-md-6 mb-3">
                                <label for="id_first_name" class="form-label">ファーストネーム*</label>
                                <input type="text" class="form-control" id="id_first_name"
                                    value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                    name="first_name"
                                    placeholder="ファーストネームを入力してください" required>
                                    {% if form.first_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_last_name" class="form-label">ラストネーム*</label>
                                <input type="text" class="form-control" id="id_last_name"
                                    value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                    name="last_name"
                                    placeholder="ラストネームを入力してください" required>
                                    {% if form.last_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_username" class="form-label">ユーザー名*</label>
                                <input type="text" class="form-control" id="id_username"
                                    value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                    name="username"
                                    placeholder="ユーザー名を入力してください" required>
                                    {% if form.username.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="id_email"
                                    value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                                    name="email"
                                    placeholder="メールアドレスを入力してください" required>
                                    {% if form.email.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_password1" class="form-label">パスワード*</label>
                                <input type="password" class="form-control" id="id_password1"
                                    value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                                    name="password1"
                                    placeholder="パスワードを入力してください" required>
                                    {% if form.password1.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_password2" class="form-label">パスワードの確認*</label>
                                <input type="password" class="form-control" id="id_password2"
                                    value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                                    name="password2"
                                    placeholder="もう一度パスワードを入力してください" required>
                                    {% if form.password2.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.password2.errors }}</div>
                                    {% endif %}
                            </div>
                        </div>
                        <!-- 登録ボタン -->
                        <button type="submit"
                            class="btn btn-dark btn-block">登録</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Project/users/templates/users/users_cart.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}

{% block content %}
{% user_carts request as carts %}
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">カート</h3>
                    <div class="container" id="cart-items-container">
                        <!-- カートの内容を表示 -->
                        {% include "cart.html" %}
                        <!-- カートの内容表示終了 -->
                    </div>
                    {% if carts %}
                    <!-- 注文確認ボタン -->
                    <a class="btn btn-dark" href="#">
                        注文確認
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}