Project/app/urls.py
from re import DEBUG
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns = [
        *urlpatterns,
    ] + debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'  # アプリケーション名を指定してURL名の衝突を防ぐ

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),  # カートに商品を追加するルート
    path('cart_change/', views.cart_change, name='cart_change'),  # カート内の商品数量を変更するルート
    path('cart_remove/', views.cart_remove, name='cart_remove'),  # カートから商品を削除するルート
]

Project/goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'  # アプリケーション名を指定してURL名の衝突を防ぐ

urlpatterns = [
    path('search/', views.catalog, name='search'),  # 検索結果を表示するルート
    path('<slug:category_slug>/', views.catalog, name='index'),  # カテゴリー別のカタログページを表示するルート
    path('product/<slug:product_slug>/', views.product, name='product'),  # 商品詳細ページを表示するルート
]

Project/goods/models.py
from django.db import models

'''
models.py (goods)

goodsアプリのデータベースモデルを定義しています。
商品モデルは、カテゴリー、在庫、価格、割引、画像などのプロパティを管理します。

DjangoのORM機能を使用して、商品とカテゴリーの管理、表示、および処理を効率的に行うことを目的としています。
'''

# カテゴリーのモデルを定義
class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='カテゴリー名') # カテゴリー名のフィールド
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL') # URL用のスラッグフィールド

    class Meta:
        db_table = 'category' # データベースのテーブル名を指定
        verbose_name = 'カテゴリー' # 管理画面での単数形の名前
        verbose_name_plural = 'カテゴリー' # 管理画面での複数形の名前

    def __str__(self):
        return self.name # 管理画面やシェルでの表示用にカテゴリー名を返す


# 商品のモデルを定義
class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='商品名') # 商品名のフィールド
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL') # URL用のスラッグフィールド
    description = models.TextField(blank=True, null=True, verbose_name='商品説明')  # 商品説明のフィールド
    image = models.ImageField(upload_to='goods_images', blank=True, null=True, verbose_name='商品画像') # 商品画像のフィールド
    price = models.DecimalField(default=0, max_digits=7, decimal_places=0, verbose_name='商品価格') # 商品価格のフィールド
    discount = models.DecimalField(default=0, max_digits=7, decimal_places=0, verbose_name='割引％') # 割引率のフィールド
    quantity = models.PositiveIntegerField(default=0, verbose_name='在庫量') # 在庫量のフィールド
    category = models.ForeignKey(to=Categories, on_delete=models.PROTECT, verbose_name='カテゴリー') # カテゴリーとの外部キー

    class Meta:
        db_table = 'product' # データベースのテーブル名を指定
        verbose_name = '商品' # 管理画面での単数形の名前
        verbose_name_plural = '商品' # 管理画面での複数形の名前
        ordering = ("id",) # デフォールト並び順をIDで設定
    
    # 管理画面の表示用に商品名と在庫数を返すメソッド
    def __str__(self):
        return f'{self.name} 在庫は{self.quantity}' 
    
    # 商品IDを5桁で表示するメソッド
    def display_id(self):
        return f'{self.id:05}'
    
    # 割引がある場合、割引後の価格を計算して返す、ない場合、そのままの価格を返すメソッド
    def sell_price(self):
        if self.discount:
            return int(round(self.price - self.price*self.discount/100, 2))
        return self.price

Project/goods/views.py
from django.core.paginator import Paginator
from django.shortcuts import get_list_or_404, render
from goods.utils import q_search
from goods.models import Products

# カタログを表示する関数
def catalog(request, category_slug=None):
    # ページ番号を取得
    page = request.GET.get('page', 1)
    on_sale = request.GET.get('on_sale', None)  # セール中の商品を表示するオプション
    order_by = request.GET.get('order_by', None)  # 並び替えオプション
    query = request.GET.get('q', None)  # 検索クエリ

    # 商品をスラッグ、クエリ、セールの状態でフィルタリングして取得
    if category_slug == 'all':
        goods = Products.objects.all()  # すべての商品を取得

    elif query:
        goods = q_search(query)  # 検索クエリに基づいて商品を検索
        
    else:
        goods = get_list_or_404(Products.objects.filter(category__slug=category_slug))  # 指定されたカテゴリーの商品を取得

    if on_sale:
        goods = goods.filter(discount__gt=0)  # セール中の商品をフィルタリング

    if order_by and order_by != 'default':
        goods = goods.order_by(order_by)  # 指定された順序で並び替え

    # ページネーションの設定
    paginator = Paginator(goods, 3)
    current_page = paginator.page(int(page))

    # コンテキストデータを作成
    context = {
        'title': 'カタログ',
        'goods': current_page,
        'slug_url': category_slug,
    }
    return render(request, 'goods/catalog.html', context)

# 商品詳細ページを表示する関数
def product(request, product_slug):
    # スラッグで特定の商品を取得
    product = Products.objects.get(slug=product_slug)
    
    # コンテキストデータを作成
    context = {
        'product': product
    }
    return render(request, 'goods/product.html', context)

Project/goods/templates/goods/catalog.html
{% extends "base.html" %}
{% load static %}
{% load goods_tags %}

{% block modal_cart %}
{% include "cart_button.html" %}
{% endblock  %}

{% block content %}
<div class="row">
    <!-- フィルターフォーム -->
    <div class="dropdown mb-2">
        <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            フィルター
        </button>

        <!-- GETでフィルターを適用するフォーム -->
        <form action="{% if request.GET.q %}{% url "catalog:search" %}{% else %}{% url "catalog:index" slug_url %}{% endif %}" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on" {% if request.GET.on_sale == 'on' %}checked{% endif %}>
                {% if request.GET.q %}
                    <input type="hidden" name="q" value="{{ request.GET.q }}">
                {% endif %}
                <label class="form-check-label" for="flexCheckDefault">
                    セール中の商品
                </label>
            </div>
            <p class="text-white mx-3 mt-3">並べ替え:</p>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default" {% if not request.GET.order_by or request.GET.order_by == 'default' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault1">
                    デフォルト順
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price" {% if request.GET.order_by == 'price' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault2">
                    安い順
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price" {% if request.GET.order_by == '-price' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault3">
                    高い順
                </label>
            </div>
            <button type="submit" class="btn btn-primary mx-3 mt-3">適用</button>
        </form>
    </div>

    <!-- 商品をループで表示 -->
     {% if not goods %}
     <h2>何も見つかっていません。</h2>
     {% endif %}
    {% for product in goods %}
    <div class="col-lg-4 col-md-6 p-4">
        <div class="card border-primary rounded custom-shadow">
            <!-- 商品画像を表示。画像がない場合は代替画像を表示 -->
            {% if product.image %}
                <a href="{% url "catalog:product" product.slug %}"><img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.image.name }}"></a>
            {% else %}
                <img src"{% static "deps/images/Not found image.png" %}" class="card-img-top">
            {% endif %}
            <div class="card-body">
                <!-- 商品名のリンク -->
                <a href="{% url "catalog:product" product.slug %}">
                    <p class="card-title">{{ product.name }}</p>
                </a>
                <!-- 商品説明を25文字まで表示 -->
                <p class="card-text">{{ product.description|truncatechars:25 }}</p>
                <p class="product_id">id:{{ product.display_id }}</p>
                <div class="d-flex justify-content-between">
                    <!-- 割引がある場合、元の価格と割引後の価格を表示 -->
                    {% if product.discount %}
                        <p><s>{{ product.price }}</s> 円</p>
                        <p><strong>{{ product.sell_price }} 円</strong></p>
                        <span class="badge bg-warning text-dark">{{ product.discount }}%割引</span>
                    {% else %}
                        <p><strong>{{ product.price }}円</strong></p>
                    {% endif %}
                    <!-- カートに追加ボタン -->
                    <a href="{% url "cart:cart_add"%}" class="btn add-to-cart"
                    data-product-id="{{ product.id }}">
                        {% csrf_token %}
                        <img class="mx-1" src="{% static "deps/icons/cart-plus.svg" %}" alt="Catalog Icon"
                            width="32" height="32">
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<!-- ページネーション -->
 {% if goods.has_previous or goods.has_next %}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center my-4">
        <div class="custom-shadow d-flex">
            <!-- 前のページへのリンク -->
            <li class="page-item {% if not goods.has_previous %}disabled{% endif %}">
              <a class="page-link" href="{% if goods.has_previous %}?{% change_params page=goods.previous_page_number %} 
              {% else %}
              #
              {% endif %}">前のページ</a>
            </li>
            
            <!-- ページ番号のリンク。現在のページを中心に前後2ページ分を表示 -->
            {% for page in goods.paginator.page_range %}
                {% if page >= goods.number|add:-2 and page <= goods.number|add:2 %}
                    <li class="page-item {% if goods.number == page %} active {% endif %}">
                        <a class="page-link" href="?{% change_params page=page %}">{{ page }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            <!-- 次のページへのリンク -->
            <li class="page-item {% if not goods.has_next %}disabled{% endif %}">
                <a class="page-link" href="{% if goods.has_next %}?{% change_params page=goods.next_page_number %}         
                {% else %}
                #
                {% endif %}">次のページ</a>
            </li>
        </div>
    </ul>
</nav>
{% endif %}
{% endblock %}

Project/goods/templates/goods/product.html
{% extends "base.html" %}
{% load static %}

{% block modal_cart %}
{% include "cart_button.html" %}
{% endblock  %}

{% block content %}
<div class="container mt-5">
    <div class="card mb-4 custom-shadow">
        <div class="row">
            <!-- 商品画像のサムネイル -->
            <div class="col-md-4">
                <img src="{{ product.image.url }}"
                    class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
            </div>
            <div class="col-md-4">
                <!-- 商品IDを表示 -->
                <p class="product_id mt-3">id:{{ product.display_id }}</p>
            </div>
            <!-- モーダルウィンドウで画像を拡大表示 -->
            <div class="modal fade" id="imageModal1" tabindex="-1"
                aria-labelledby="imageModal1Label" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="imageModal1Label">画像1</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                aria-label="閉じる"></button>
                        </div>
                        <div class="modal-body">
                            <!-- モーダルウィンドウで拡大表示される画像 -->
                            <img src="{{ product.image.url }}"
                                class="img-fluid" alt="{{ product.name }}">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- 商品の詳細説明 -->
        <div class="card-body">
            <p class="card-text">値段: <strong>{{ product.sell_price }}円</strong></p>
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text">{{ product.description }}</p>
            <!-- カートに追加ボタン -->
            <a href="{% url "cart:cart_add" %}" class="btn btn-dark add-to-cart" data-product-id="{{ product.id }}">
                {% csrf_token %}
                カートに追加する
            </a>
        </div>
    </div>
</div>
{% endblock %}