Project/app/urls.py
from re import DEBUG
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns = [
        *urlpatterns,
    ] + debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'  # アプリケーション名を指定してURL名の衝突を防ぐ

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),  # カートに商品を追加するルート
    path('cart_change/', views.cart_change, name='cart_change'),  # カート内の商品数量を変更するルート
    path('cart_remove/', views.cart_remove, name='cart_remove'),  # カートから商品を削除するルート
]

Project/carts/models.py
from django.db import models
from goods.models import Products
from users.models import User

# カート用のカスタムクエリセット
class CartQuerySet(models.QuerySet):
    
    # カート内の商品の合計金額を計算するメソッド
    def total_price(self):
        return int(sum(cart.products_price() for cart in self))
    
    # カート内の商品の合計数量を計算するメソッド
    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0

# カートモデルの定義
class Cart(models.Model):

    user = models.ForeignKey(to=User, on_delete=models.CASCADE, blank=True, null=True, verbose_name='ユーザー')
    product = models.ForeignKey(to=Products, on_delete=models.CASCADE, verbose_name='注文品')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='数量')
    session_key = models.CharField(max_length=32, null=True, blank=True)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='追加した日付')

    class Meta:
        db_table = 'cart'  # データベースのテーブル名
        verbose_name = 'カート'  # 管理画面での単数形の名前
        verbose_name_plural = 'カート'  # 管理画面での複数形の名前

    # カスタムクエリセットをオブジェクトマネージャーとして使用
    objects = CartQuerySet().as_manager()

    # カート内の商品の総価格を計算するメソッド
    def products_price(self):
        return int(round(self.product.sell_price() * self.quantity, 2))

    # オブジェクトの文字列表現を定義
    def __str__(self):
        return f'{self.user.username}のカート | 商品 - {self.product.name} | 数量 - {self.quantity}'

Project/carts/views.py
from math import prod
from urllib import response
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from carts.utils import get_user_carts
from carts.models import Cart
from goods.models import Products

# カートに商品を追加する関数
def cart_add(request):
    product_id = request.POST.get("product_id")  # リクエストから商品IDを取得
    product = Products.objects.get(id=product_id)  # 商品IDで商品をDBから取得

    if request.user.is_authenticated:  # ユーザーが認証済みか確認
        carts = Cart.objects.filter(user=request.user, product=product)  # ユーザーのカートを取得

        if carts.exists():  # すでにカートに商品が存在する場合
            cart = carts.first()  # 最初のカートアイテムを取得
            if cart:
                cart.quantity += 1  # 商品の数量を増加
                cart.save()
        else:
            Cart.objects.create(user=request.user, product=product, quantity=1)  # 新しいカートアイテムを作成

    user_cart = get_user_carts(request)  # ユーザーのカートを取得

    # カートのHTMLをレンダリング
    cart_items_html = render_to_string(
        "cart.html", {"carts": user_cart}, request=request)
    
    response_data = {
        "message": "カートに追加されました",  # メッセージ
        "cart_items_html": cart_items_html,  # レンダリングされたカートのHTML
    }

    return JsonResponse(response_data)  # JSONレスポンスを返す

# カート内の商品数量を変更する関数
def cart_change(request):
    cart_id = request.POST.get("cart_id")  # リクエストからカートIDを取得
    quantity = request.POST.get("quantity")  # リクエストから新しい数量を取得

    cart = Cart.objects.get(id=cart_id)  # カートアイテムを取得

    cart.quantity = quantity  # 数量を更新
    cart.save()
    updated_quantity = cart.quantity  # 更新後の数量を取得

    cart = get_user_carts(request)  # ユーザーのカートを取得
    cart_items_html = render_to_string(
        "cart.html", {"carts": cart}, request=request)
    
    response_data = {
        "message": "数量が変更されました",  # メッセージ
        "cart_items_html": cart_items_html,  # レンダリングされたカートのHTML
        "quantity": updated_quantity,  # 更新された数量
    }

    return JsonResponse(response_data)  # JSONレスポンスを返す

# カートから商品を削除する関数
def cart_remove(request):
    cart_id = request.POST.get("cart_id")  # リクエストからカートIDを取得

    cart = Cart.objects.get(id=cart_id)  # カートアイテムを取得
    quantity = cart.quantity  # 削除する前の数量を取得
    cart.delete()  # カートアイテムを削除

    user_cart = get_user_carts(request)  # ユーザーのカートを取得
    cart_items_html = render_to_string(
        "cart.html", {"carts": user_cart}, request=request)
    
    response_data = {
        "message": "商品は削除されました",  # メッセージ
        "cart_items_html": cart_items_html,  # レンダリングされたカートのHTML
        "quantity_deleted": quantity,  # 削除された数量
    }

    return JsonResponse(response_data)  # JSONレスポンスを返す

Project/carts/templates/cart.html
{% load static %}

{% if user.is_authenticated %}
<div class="card mb-3 text-bg-light shadow-lg">
    {% for cart in carts %}
        <div class="card-header">
            <h5 class="card-title">{{ cart.product.name }}</h5> <!-- 'card.product.name' должно быть 'cart.product.name' -->
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <div class="row text-center">
                    <div class="col p-0">
                        <div class="input-group">
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-dark btn-sm decrement"
                                    data-cart-id="{{ cart.id }}" data-cart-change-url="{% url "cart:cart_change" %}">
                                    {% csrf_token %}
                                    -</button>
                            </span>
                            <input type="text" class="form-control number" value="{{ cart.quantity }}"
                                readonly>
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-dark btn-sm increment"
                                    data-cart-id="{{ cart.id }}" data-cart-change-url="{% url "cart:cart_change" %}">
                                    {% csrf_token %}
                                    +</button>
                            </span>
                        </div>
                    </div>
                    <div class="col p-0">
                        <p>{{ cart.product.sell_price }}円 = </p> <!-- 商品の単価を表示 -->
                    </div>
                    <div class="col p-0"><strong>{{ cart.products_price }}円</strong></div> <!-- 合計価格を表示 -->
                    <div class="col p-0">
                        <a href="{% url "cart:cart_remove"%}" class="remove-from-cart" data-cart-id="{{ cart.id }}">
                            {% csrf_token %}
                            <img class="mx-1" src="{% static "deps/icons/trash3-fill.svg" %}"
                                alt="Catalog Icon" width="16" height="16">
                        </a>
                    </div>
                </div>
            </li>
        </ul>
    {% endfor %}
</div>
<div class="card mb-3 shadow-lg">
    <div class="card-footer">
        <p class="float-left">全部で <strong>{{ carts.total_quantity }}</strong>つの商品です。合計金額は以下になります。</p> <!-- 合計数量 -->
        <h4 class="float-left"><strong>{{ carts.total_price }}円</strong></h4> <!-- 合計価格 -->
    </div>
</div>
{% else %}
<h5>カートに追加するにはログインが必要です。</h5>
<p>ログイン又は新規登録してください。</p>
{% endif %}